$(document).ready(function(){
    $(".hide-des").hover(function(){
        $(".show-des").toggle()
        $(".hide-des").toggle()
    })
    $(".hide-dev").hover(function(){
        $(".show-dev").toggle()
        $(".hide-dev").toggle()
    })
    $(".hide-pm").hover(function(){
        $(".show-pm").toggle()
        $(".hide-pm").toggle()
    })
})