$(document).ready(function(){
    $(".hide-des").click(function(){
        $(".show-des").toggle()
        $(".hide-des").toggle()
    })
    $(".hide-dev").click(function(){
        $(".show-dev").toggle()
        $(".hide-dev").toggle()
    })
    $(".hide-pm").click(function(){
        $(".show-pm").toggle()
        $(".hide-pm").toggle()
    })
})